[package]
name = "botagent"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
pcre2 = "0.2.9"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"

[dev-dependencies]
tempfile = "3.12.0"
